name: CI

on:
  push:
    branches:
      - main
      - "**"
  pull_request:

jobs:
  frontend:
    name: Frontend Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies (root)
        run: npm ci
        working-directory: .
      - name: Lint (frontend)
        run: npm --prefix frontend run lint
      - name: Build (frontend)
        run: npm --prefix frontend run build

  backend:
    name: Backend Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies (root)
        run: npm ci
        working-directory: .
      - name: Lint (backend)
        run: npm --prefix backend run lint
      - name: Build (backend)
        run: npm --prefix backend run build
