name: Daily Postgres Backup

on:
  schedule:
    - cron: '0 3 * * *' # 03:00 UTC daily
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client gzip

      - name: Run backup script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          bash ./scripts/backup-db.sh

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup-${{ github.run_id }}
          path: backups/*.sql.gz
          retention-days: 7

